name: Nilgiri_Automation

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      custom_feature_file:
        description: 'Custom feature file to run test'
        required: false
        default: ''
  schedule:
    - cron: '0 0 31 11 *'  # Run every night at midnight UTC

jobs:
  run_sanity_test_on_dev_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm run nilgiriDependencyInstall

      - name: Install Playwright
        run: npx playwright install

      - name: Run Sanity Tests
        run: npm run sanityTests
  run_single_file_with_curl:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.custom_feature_file || '') != ''
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm run nilgiriDependencyInstall

      - name: Install Playwright
        run: npx playwright install
        #Please give $ in front of {{ github.event.inputs.custom_feature_file }} in your real yml file
      - name: Run Single File with Curl
        run: |
          echo "Running custom feature file: ${{ github.event.inputs.custom_feature_file }}"
          npm run cucumberRun "${{ github.event.inputs.custom_feature_file }} -- --headed=false || true"
      - name: Generete Report
        run: npm run posttest
  run_daily_build:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == 'cron(0 0 * * *)'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm run nilgiriDependencyInstall

      - name: Install Playwright
        run: npx playwright install

      - name: Run Daily Build
        run: npm run automation -- --headed=false
  run_tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.custom_feature_file || '') == ''
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm run nilgiriDependencyInstall

      - name: Install Playwright
        run: npx playwright install

      - name: Run Tests
        run: npm run automation --headed=true
  run_cucumber_feature:
          runs-on: ubuntu-latest
          if: github.event.workflow_run.event == 'workflow_dispatch' && github.event.inputs.custom_feature_file
          steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
      
            - name: Install Dependencies
              run: npm run automation --headed=false  # Modify this based on your project setup
      
            - name: Run Cucumber Feature
              run: npm run cucumberRun "${{ github.event.inputs.custom_feature_file }}|| true"
            - name: Generete Report
              run: npm run posttest
  